---
kind: pipeline
type: docker
name: default


steps:
- name: build
  image: docker:bash
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
#  - name: docker_config
#    path: /docker_config/config.json
  commands:
   - echo building stuff...
#  - export DOCKER_CONFIG=/docker_config
#  - ./build_docker.sh
#  - docker push registry.lph.zone:5000/calimo:${DRONE_BRANCH}

- name: test
  image: ubuntu:latest
  pull: always
  commands:
  - echo testin stuff...

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
