---
kind: pipeline
type: docker
name: default


steps:
- name: build
  image: ocaml/opam:opensuse-ocaml-5.0
  environment:
    USERNAME:
        from_secret: docker_username
    TOKEN:
        from_secret: docker_token
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
#  - name: docker_config
#    path: /docker_config/config.json
  commands:
   - echo building stuff...
   - docker build -t blog .
   - docker login -u $USERNAME -p $TOKEN
   - docker push push ropianos/blog:${DRONE_BRANCH}
#  - export DOCKER_CONFIG=/docker_config
#  - ./build_docker.sh
#  - docker push registry.lph.zone:5000/calimo:${DRONE_BRANCH}

- name: test
  image: ubuntu:latest
  pull: always
  commands:
  - echo testin stuff...
  - cat testing

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
